### ISSUE TITLE
Corriger image importation

### ISSUE THREAD

**Issue by TheArchightech** [Giant-T/guac-a-mole#22]
Nous avons malheureusement inclus les mauvaise image dans le projet, ceux qui était dans le projet whack a mole(whack-a-mole/images). Nous devons supprimer ceux si et ajouter à la place ceux du dossier play (whack-a-mole/play/images). Pour importer comme il faut nous devons modifier le dossier .yaml

**Comment by Giant-T** [comment]
Parfait on regardera ça demain
